export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES'
export const FETCH_EMPLOYEES_SUCCEED = 'FETCH_EMPLOYEES_SUCCEED'
export const FETCH_EMPLOYEES_FAILED = 'FETCH_EMPLOYEES_FAILED'

export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
export const CREATE_EMPLOYEE_SUCCEED = 'CREATE_EMPLOYEE_SUCCEED'
export const CREATE_EMPLOYEE_FAILED = 'CREATE_EMPLOYEE_FAILED'

export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE'
export const EDIT_EMPLOYEE_SUCCEED = 'EDIT_EMPLOYEE_SUCCEED'
export const EDIT_EMPLOYEE_FAILED = 'EDIT_EMPLOYEE_FAILED'

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
export const DELETE_EMPLOYEE_SUCCEED = 'DELETE_EMPLOYEE_SUCCEED'
export const DELETE_EMPLOYEE_FAILED = 'DELETE_EMPLOYEE_FAILED'
