export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES'
export const FETCH_EMPLOYEES_SUCCEED = 'FETCH_EMPLOYEES_SUCCEED'
export const FETCH_EMPLOYEES_FAILED = 'FETCH_EMPLOYEES_FAILED'

export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
export const CREATE_EMPLOYEE_SUCCEED = 'CREATE_EMPLOYEE_SUCCEED'
export const CREATE_EMPLOYEE_FAILED = 'CREATE_EMPLOYEE_FAILED'
